name: ai_kart_trends
on:
  schedule:
    - cron: "15,45 0-14 * * *"
  workflow_dispatch:

jobs:
  okera:
    name: ai_kart_trends
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: twitter key decode
        env:
          JSON_DECODE: ${{ secrets.AI_KART_INI }}

        run: |
          echo -n $JSON_DECODE | base64 --decode > ./ai_kart.ini

      - name: pip install
        run: pip install --upgrade pip && pip install -r requirements.txt && pip install --upgrade openai

      - name: schedule_evil_tweet
        if: github.event_name != 'workflow_dispatch'
        run: |
          python ai_kart_trend.py
        env:
          gpt_api_key: ${{ secrets.GPT_API_KEY }}

      - name: workflow_dispatch_evil_tweet
        if: github.event_name == 'workflow_dispatch'
        id: workflow_dispatch_evil_tweet
        run: |
          python ai_kart_trend.py
        env:
          gpt_api_key: ${{ secrets.GPT_API_KEY }}
